#! /bin/sh
#  /etc/init.d/agorad

### BEGIN INIT INFO
# Provides:          agorad
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $time mysql
# Should-Stop:       $network $time mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Handles the AgoraServer daemon
# Description:       Uses jsvc to handle the Java implementation of the
#                    AgoraServer daemon. Needs connection to database.
### END INIT INFO	

# Author:   Agora Project
# Url:      https://github.com/Agora-Project/AgoraDevDocs/wiki

# Credits to Sheldon Neilson for his article (http://www.neilson.co.za/?p=253)

. /lib/lsb/init-functions

NAME="agorad"
DESC="JAgoraServer Daemon"

# The path to Jsvc
JSVC="/usr/bin/jsvc"

# The path to the folder containing MyDaemon.jar
FILE_PATH="/usr/lib/agora"

# The path to the folder containing the java runtime
# This is assumed to be defined. Otherwise define it here.
JAVA_HOME="/usr/lib/jvm/java-6-openjdk-amd64"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/JAgoraServer.jar:$FILE_PATH/lib/commons-daemon-1.0.15.jar"

# The fully qualified name of the class to execute
CLASS="org.agora.server.JAgoraServer"

# Any command line arguments to be passed to the our Java Daemon implementations init() method 
ARGS=""

#The user to run the daemon as
USER="root"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="/var/log/$NAME.log"

# System.err writes to this file...
LOG_ERR="/var/log/$NAME.err"

jsvc_exec()
{   
	echo $JSVC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS 
    $JSVC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)  
        echo -n "[$DESC] Starting..."        
        
        # Start the service
        jsvc_exec
        
        echo " done."
    ;;
    stop)
        echo -n "[$DESC] Stopping..."
        
        # Stop the service
        jsvc_exec "-stop"       
        
        echo " done."
    ;;
    restart)
        if [ -f "$PID" ]; then
            
            echo "[$DESC] Restarting..."
            
            # Stop the service
            jsvc_exec "-stop"
            
            # Start the service
            jsvc_exec
            
            echo " done."
        else
            echo "[$DESC] Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0